name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log